name: Bad CI

on:
  push:

jobs:
  bad_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "latest"   # ❌ нефиксированная версия

      - name: Install dependencies
        run: |
          pip install -r requirements.txt   # ❌ без кеша, без контроля версий

      - name: Run application
        run: |
          python taskly.py --help           # ❌ “build” и “test” смешаны

      - name: Deploy
        run: |
          echo "Deploying to production"    # ❌ всегда, из любой ветки
