name: Bad CI

on:
  push:
    branches: [ main, bad-ci ]
  pull_request:
    branches: [ main, bad-ci ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install linter and formatter
        run: |
          python -m pip install --upgrade pip
          pip install ruff black

      - name: Run linter (ruff)
        run: ruff .

      - name: Check code formatting (black)
        run: black --check .

      - name: Install project dependencies  # ❌ без кеша, без контроля версий
        run: pip install -r requirements.txt

      - name: Run application  # ❌ “build” и “test” смешаны
        run: python taskly.py --help

      - name: Deploy  # ❌ выполняется всегда, из любой ветки
        run: echo "Deploying to production"

      - name: Install Python latest  # ❌ нефиксированная версия
        uses: actions/setup-python@v5
        with:
          python-version: "latest"
